on:
  push:
  workflow_dispatch:

jobs:
  docker:
    name: Push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract metadata (tags, labels) for PHP
        id: phpmeta
        uses: docker/metadata-action@v5
        with:
          images: vrokdd/php
          tags: |
            type=ref,event=branch
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            latest=auto

      - name: Build and push PHP image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.phpmeta.outputs.tags }}
          labels: ${{ steps.phpmeta.outputs.labels }}
          cache-from: type=registry,ref=vrokdd/php
          cache-to: type=inline
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
